### ISSUE TITLE
Emoji Translation Issues in Manual Cross-Post Function

### ISSUE THREAD

**Issue by toddgrotenhuis** [microdotblog/issues#250] opened 2024-02-07 17:24 UTC
Emoji become the "black diamond ?" when using the new manual cross-post option.

E.g.

<img width="1006" alt="image" src="https://github.com/microdotblog/issues/assets/165077/e36892aa-1841-4f39-a8c0-fa28eda30183">

<img width="664" alt="image" src="https://github.com/microdotblog/issues/assets/165077/b9be23fb-3b8b-4187-ab4f-b1e7c9be3eed">

It doesn't appear to be due lack of compatibility, because they can be instantly fixed on the other app, but it does currently require redoing the emoji.

**Comment by manton** [comment] 2024-02-07 17:27
Thanks, I can confirm this. It doesn't appear to happen for the manual Twitter X option, but it does for Threads. Hopefully something we can work around, if it's not a Threads bug.

**Comment by manton** [comment] 2024-02-09 04:15
I asked a Threads developer about this, and he confirmed it's a known issue with the web version of Threads. So, I'm going to close this since there's nothing Micro.blog can do. Should just start working whenever Threads has a fix ready.

**Closed as completed by manton** 2024-02-09 04:15 UTC
