### ISSUE TITLE
More posts visible in timeline

### ISSUE THREAD

**Issue by jeanmacd** [microdotblog/issues#58] opened 2017-06-15 15:23 UTC
It appears the current limit of visible posts is 25 recent posts or mentions. Need to be able to scroll back further. Could be limited to a time frame (1 week would be nice, in order to catch up after a vacation, for example).

**Comment by jstr** [comment] 2017-09-06 23:08
Related/duplicate of #33

**Comment by manton** [comment] 2018-02-12 16:45
You can now scroll further back.

**Closed as completed by manton** 2018-02-12 16:45 UTC
